baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "â†©"
googleAnalytics = "G-Q1WHKR2FB3"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = ""
title = "Avm"
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Categories"
url = "/categories/"
[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2
[[menu.feed]]
name = "Subscribe"
url = "/index.xml"

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = " | Adrian Villanueva | Any and all opinions listed here are my own."

